
plugins:
  - jekyll-remote-theme
  
#theme: jekyll-theme-minimal
title: Baie Vivante et Solidaire
description: Baie Vivante et Solidaire est une association du territoire de la Baie du Cotentin
remote_theme: hydecorp/hydejack@latest
